### ISSUE TITLE
Investigate the template that came with Jesse's repo

### ISSUE THREAD

**Issue by keithamoss** [govhackaustralia/govhackaustralia.github.io#13]
Is it hand-built or based on something else? Is there a newer version? et cetera

**Comment by keithamoss** [comment]
Is there documentation for Rasmus Andersson's template, @jesserobertson? (A quick Google says no.)

**Comment by jesserobertson** [comment]
Don't think so. I pretty much just looked through his git repo for info.

**Comment by keithamoss** [comment]
Closed by e613ba9 and the move to Bootstrap.

**Comment by keithamoss** [comment]
Err, I mean e70aa11.
