### ISSUE TITLE
readme.md

### ISSUE THREAD

**Issue by chris-beer** [govhackaustralia/govhackaustralia.github.io#137]
The link to the GovHack Data Model (https://www.lucidchart.com/documents/edit/d36186be-0c77-4e89-a735-6022a716566a) appears to require a paid account - using 3rd party auth (Google) doesn't appear to give access?

**Comment by alansfyeung** [comment]
I think Keith dumped this into a huge PNG at one stage which would be sitting on our Google drive somewhere. Perhaps we should publish it formally somewhere...

**Comment by keithamoss** [comment]
Yeah, let's publish this formally..but it needs updating first to reflect the reality of what has happened since we put it together.
