### ISSUE TITLE
Indicate the importance of a location

### ISSUE THREAD

**Issue by alansfyeung** [govhackaustralia/govhackaustralia.github.io#82]
In `/feed/locations/all.json` can we add a field for `priority`. We'd tie it to a simple convention such as lower numbers = display above, and lower numbers = display below. E.g.

+ Official Event in cap city  = 10
+ Official event = 20
+ Node event in cap city = 30

etc

**Comment by keithamoss** [comment]
Merge in #89.

**Comment by alansfyeung** [comment]
#92 is WIP
