### ISSUE TITLE
Try out Alan's site switcher

### ISSUE THREAD

**Issue by keithamoss** [govhackaustralia/govhackaustralia.github.io#90]
https://github.com/govhackaustralia/asset-server#govhack-site-switcher

**Comment by keithamoss** [comment]
Implemented!

I've got an enhancement request though :)

https://github.com/govhackaustralia/asset-server/issues/1

**Comment by alansfyeung** [comment]
FYI, made an asset-server-side CSS change which will set `position: fixed` if there is a class of `is-fixed`

So no Jabberwocky css change needed.

**Comment by keithamoss** [comment]
How do I set `is-fixed` w/o doing the setInterval hack tho? :)
